# 파일 규격 버전
version: '3.1'
# 이 항목 밑에 실행하려는 컨테이너 들을 정의
services:
  mariadb: # 서비스명
    image: 'mariadb:${MARIA_TAG}' # 사용할 이미지
    container_name: mariadb
    ports:
      - '${MARIA_PORT}:3306'
    environment:
      MARIADB_ROOT_PASSWORD: '${MARIA_PASS}'
      TZ: Asia/Seoul
  mongodb:
    image: 'mongo:${MONGO_TAG}'
    container_name: mongodb
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASS}'
